name: ci # name of the workflow
on: [push, pull_request, workflow_dispatch] # event(s) that triggers the workflow
jobs:
  test: # name of the job. child keys define properties of the job. 
    runs-on: ubuntu-latest # virtaual machine the job will run on
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # An action that checks out the repository onto the runner, allowing it to run scripts or other actions against the repo code. should always be included. https://github.com/marketplace/actions/checkout
      
      - name: Set up Python
        uses: actions/setup-python@v4 # Setting up Python, pip and pypi: https://github.com/marketplace/actions/setup-python
        with: 
          python-version: "3.9"
      
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Test with PyTest
        run: | 
          pytest

# cache dependencies etc.: https://docs.github.com/en/actions/using-workflows
# examples: https://docs.github.com/en/actions/examples/