name: jpap-ci

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    branches: [main]

jobs:
  
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.9"
      
      - name: Cache dependencies
        uses: actions/cache@v3
        id: restore-cache
        with:
          path: ${{ env.pythonLocation }}
          key: python-dependencies-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if: steps.restore-cache.outputs.cache-hit != 'true'
      
      - name: Test with PyTest
        run: | 
          python -m pytest